### PR TITLE
Fixes take root stand up bug (2) 

### PR DESCRIPTION
**Pull request by mrbermell**
Solves issue #187 and replaces PR #196

### CODE REVIEW

**Comment by mrbermell** [comment]
I think this is ready to merge and quite important because is has crucial fixes for the scripted bot too.

**Comment by mrbermell** [comment]
There's a problem with this the additions in the Player-class. num_moves_left() can return negative values if the `include_gfi`is not set. I think that is not how you would expect the function to work. It also brakes the "movement left" layer which can then return negative values.  And num_gfi_left() seems to work according to the principle that num_moves_left returns negative values. 

```python
def num_moves_left(self, include_gfi: bool = False):
    if self.state.taken_root:
        return 0
    if self.state.used or self.state.stunned:
        moves = 0
    else:
        moves = self.get_ma()
        moves = moves - self.state.moves
        if include_gfi:
            if self.has_skill(Skill.SPRINT):
                moves = moves + 3
            else:
                moves = moves + 2
    return max(0, moves)

def num_gfis_left(self):
    ma = self.num_moves_left()
    gfis_used = 0 if ma >= 0 else -ma
    if self.has_skill(Skill.SPRINT):
        return 3 - gfis_used
    elif self.state.taken_root:
        return 0
    return 2 - gfis_used
```

**Comment by mrbermell** [comment]
I've pushed my solution proposal: 

```python
def num_moves_left(self, include_gfi: bool = False):
    if self.state.taken_root or self.state.used or self.state.stunned:
        return 0
    moves = self.get_ma() - self.state.moves
    if include_gfi:
        if self.has_skill(Skill.SPRINT):
            moves = moves + 3
        else:
            moves = moves + 2
    return moves

def num_gfis_left(self):
    return self.num_moves_left(include_gfi=True) - self.num_moves_left(include_gfi=False)
```

**Comment by mrbermell** [comment]
> Looks right but check if anything is expecting it to be lease than 0 if GFI is used. This would be bad of course but I have a vague memory of doing this at some point.

Only `num_gfis_left()` which used the negative values, but as stated, that is fixed. I did check the rest of the code, it's fine.

**Comment by njustesen** [comment]
There are no more teams with a Treeman?

**Comment by mrbermell** [comment]
Huh?

**Review by njustesen — APPROVED** [review]
Looks good!

Screenshot 2022-02-14 at 00 02 47

**Comment by njustesen** [comment]
> Huh?

Nevermind :)

**Pull request merged**
