### PR TITLE
Forward model update and optimizations

### PR DESCRIPTION
**Pull request by mrbermell**
This PR should be considered after PRs #191 and #190 have been merged (they have been merged now). This branch is built on top of those changes. 

This PR contains: 
1. Feature to step the game state forward after being reverted. 
2. New ways to set classes in `models.py` to immutable using decorators instead of inheritence which speeds up execution and readability. 
3. Some general optimizations of forward_model.py, game.py, procedures.py, pathfinding.py

### CODE REVIEW

**Comment by mrbermell** [comment]
I'm going insane, here's some [rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging) mumbling that hopefully makes me solve this. Github test suite _always_ crashes with a Segmentation Fault. It crashes in test_revert_and_forward() in test_forward_model.py while comparing two MoveAction-procedure's paths attributes. Since the paths are from cython_pathfinding.pyx it's harder to debug, it becomes harder and stranger that I only _sometimes_  (<10% of the time) get this fault on my computer. 

More specifically it crashes while calling `assert_game_states` game states for the last time in the loop. That function hasn't changed for a long time. The only change is this tests which now also tests `game.forward(undone_steps)`. But I just don't see it. 

```
============================= test session starts ==============================
platform linux -- Python 3.7.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/runner/work/botbowl/botbowl
collected 448 items

tests/ai/test_competition.py ..                                          [  0%]
tests/ai/test_env.py .                                                   [  0%]
tests/ai/test_pathfinding.py ........................................... [ 10%]
...........                                                              [ 12%]
Fatal Python error: Segmentation fault

Current thread 0x00007f4f5a0b2740 (most recent call first):
  File "/home/runner/work/botbowl/botbowl/botbowl/core/util.py", line 136 in compare_iterable
  File "/home/runner/work/botbowl/botbowl/botbowl/core/util.py", line 129 in compare_iterable
  File "/home/runner/work/botbowl/botbowl/botbowl/core/util.py", line 157 in compare_object
  File "/home/runner/work/botbowl/botbowl/botbowl/core/procedure.py", line 60 in compare
  File "/home/runner/work/botbowl/botbowl/botbowl/core/util.py", line 122 in compare_iterable
  File "/home/runner/work/botbowl/botbowl/botbowl/core/util.py", line 133 in compare_iterable
  File "/home/runner/work/botbowl/botbowl/botbowl/core/model.py", line 509 in compare
  File "/home/runner/work/botbowl/botbowl/tests/framework/test_forward_model.py", line 152 in assert_game_states
  File "/home/runner/work/botbowl/botbowl/tests/framework/test_forward_model.py", line 31 in test_revert_and_forward
```

**Comment by mrbermell** [comment]
i had made a mistake when implementing cython_pathfinding.Path.\_\_reduce__() that only showed when a Path without a collected path was pickled. And then, once pickled, it caused a segmentation fault in the c code when it tried to collect the path. 

Anyways, all solved now. And this error is not present in the python implementation because it doesn't use a custom \_\_reduce__()

**Comment by njustesen** [comment]
Remember to update https://njustesen.github.io/botbowl/forward-model.html

**Comment by njustesen** [comment]
Depends on #190 and #191

**Comment by mrbermell** [comment]
@njustesen , I just merged the latest updates from the master branch and updated the tutorial. With that I think it's ready for thorough review.

**Review by njustesen — APPROVED** [review]
Great work!

My only request is to add the results of the performance tests and ideally compare them to before, if possible.

**Comment by mrbermell** [comment]
Here's the benchmark as run on [branch before merge](https://github.com/njustesen/botbowl/commit/379d23ff136f54fcb286c2caf812858acfb1b087). 
```
10 games without forward model: 1.27 seconds
10 games with forward model: 1.84 seconds
``` 

Here's the benchmark as run on this branch: 
```
10 games without forward model: 0.76 seconds
10 games with forward model: 1.28 seconds
```

Without forward model enabled it is 1.67x  faster  (1.27/0.76). 

With forward model enabled it's 1.44x  faster  (1.84/1.28).

**Pull request merged**
